language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t bencochrane1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bencochrane1/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-502377633955"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"